# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XmppApp5_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(607, 527)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/xmpp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QGroupBox {\n"
"qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(70, 126, 176, 100), stop:1 rgba(255, 255, 255, 255))qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(70, 126, 176, 100), stop:1 rgba(255, 255, 255, 100))\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Credentials = QtGui.QTabWidget(self.centralwidget)
        self.Credentials.setEnabled(True)
        self.Credentials.setObjectName(_fromUtf8("Credentials"))
        self.tab_basic = QtGui.QWidget()
        self.tab_basic.setObjectName(_fromUtf8("tab_basic"))
        self.gb_general = QtGui.QGroupBox(self.tab_basic)
        self.gb_general.setGeometry(QtCore.QRect(10, 10, 571, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_general.sizePolicy().hasHeightForWidth())
        self.gb_general.setSizePolicy(sizePolicy)
        self.gb_general.setObjectName(_fromUtf8("gb_general"))
        self.cb_dns = QtGui.QCheckBox(self.gb_general)
        self.cb_dns.setGeometry(QtCore.QRect(450, 130, 77, 17))
        self.cb_dns.setChecked(True)
        self.cb_dns.setObjectName(_fromUtf8("cb_dns"))
        self.lbl_dns = QtGui.QLabel(self.gb_general)
        self.lbl_dns.setGeometry(QtCore.QRect(19, 125, 55, 16))
        self.lbl_dns.setObjectName(_fromUtf8("lbl_dns"))
        self.le_dns = QtGui.QLineEdit(self.gb_general)
        self.le_dns.setGeometry(QtCore.QRect(100, 120, 133, 20))
        self.le_dns.setObjectName(_fromUtf8("le_dns"))
        self.lbl_tls = QtGui.QLabel(self.gb_general)
        self.lbl_tls.setGeometry(QtCore.QRect(19, 171, 71, 16))
        self.lbl_tls.setObjectName(_fromUtf8("lbl_tls"))
        self.cb_tls = QtGui.QComboBox(self.gb_general)
        self.cb_tls.setGeometry(QtCore.QRect(100, 170, 89, 20))
        self.cb_tls.setObjectName(_fromUtf8("cb_tls"))
        self.cb_tls.addItem(_fromUtf8(""))
        self.cb_tls.addItem(_fromUtf8(""))
        self.cb_tls.addItem(_fromUtf8(""))
        self.lbl_server1 = QtGui.QLabel(self.gb_general)
        self.lbl_server1.setGeometry(QtCore.QRect(19, 32, 41, 16))
        self.lbl_server1.setObjectName(_fromUtf8("lbl_server1"))
        self.le_server1_hn = QtGui.QLineEdit(self.gb_general)
        self.le_server1_hn.setGeometry(QtCore.QRect(100, 32, 133, 20))
        self.le_server1_hn.setObjectName(_fromUtf8("le_server1_hn"))
        self.le_server1_ip = QtGui.QLineEdit(self.gb_general)
        self.le_server1_ip.setGeometry(QtCore.QRect(263, 32, 133, 20))
        self.le_server1_ip.setObjectName(_fromUtf8("le_server1_ip"))
        self.le_server1_dn = QtGui.QLineEdit(self.gb_general)
        self.le_server1_dn.setGeometry(QtCore.QRect(425, 32, 133, 20))
        self.le_server1_dn.setObjectName(_fromUtf8("le_server1_dn"))
        self.lbl_server2 = QtGui.QLabel(self.gb_general)
        self.lbl_server2.setGeometry(QtCore.QRect(19, 78, 41, 16))
        self.lbl_server2.setObjectName(_fromUtf8("lbl_server2"))
        self.le_server2_hn = QtGui.QLineEdit(self.gb_general)
        self.le_server2_hn.setGeometry(QtCore.QRect(100, 78, 133, 20))
        self.le_server2_hn.setObjectName(_fromUtf8("le_server2_hn"))
        self.le_server2_ip = QtGui.QLineEdit(self.gb_general)
        self.le_server2_ip.setGeometry(QtCore.QRect(263, 78, 133, 20))
        self.le_server2_ip.setObjectName(_fromUtf8("le_server2_ip"))
        self.le_server2_dn = QtGui.QLineEdit(self.gb_general)
        self.le_server2_dn.setGeometry(QtCore.QRect(425, 78, 133, 20))
        self.le_server2_dn.setObjectName(_fromUtf8("le_server2_dn"))
        self.cb_cup = QtGui.QCheckBox(self.gb_general)
        self.cb_cup.setGeometry(QtCore.QRect(450, 170, 81, 17))
        self.cb_cup.setChecked(True)
        self.cb_cup.setObjectName(_fromUtf8("cb_cup"))
        self.lbl_dns.raise_()
        self.le_dns.raise_()
        self.lbl_tls.raise_()
        self.cb_tls.raise_()
        self.lbl_server1.raise_()
        self.le_server1_hn.raise_()
        self.le_server1_ip.raise_()
        self.le_server1_dn.raise_()
        self.lbl_server2.raise_()
        self.le_server2_hn.raise_()
        self.le_server2_ip.raise_()
        self.le_server2_dn.raise_()
        self.cb_dns.raise_()
        self.cb_cup.raise_()
        self.pb_start = QtGui.QPushButton(self.tab_basic)
        self.pb_start.setGeometry(QtCore.QRect(240, 400, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pb_start.setFont(font)
        self.pb_start.setStyleSheet(_fromUtf8("QPushButton{\n"
" background: #57b5f0;\n"
"  background-image: -webkit-linear-gradient(top, #57b5f0, #0e2838);\n"
"  background-image: -moz-linear-gradient(top, #57b5f0, #0e2838);\n"
"  background-image: -ms-linear-gradient(top, #57b5f0, #0e2838);\n"
"  background-image: -o-linear-gradient(top, #57b5f0, #0e2838);\n"
"  background-image: linear-gradient(to bottom, #57b5f0, #0e2838);\n"
"  border-radius: 28px;\n"
"  font-family: Arial;\n"
"  color: #ffffff;\n"
"  font-size: 15px;\n"
"  padding: 3px 20px 3px 20px;\n"
"  text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background: #3cb0fd;\n"
"  background-image: -webkit-linear-gradient(top, #3cb0fd, #3498db);\n"
"  background-image: -moz-linear-gradient(top, #3cb0fd, #3498db);\n"
"  background-image: -ms-linear-gradient(top, #3cb0fd, #3498db);\n"
"  background-image: -o-linear-gradient(top, #3cb0fd, #3498db);\n"
"  background-image: linear-gradient(to bottom, #3cb0fd, #3498db);\n"
"  text-decoration: none;\n"
"}"))
        self.pb_start.setDefault(False)
        self.pb_start.setFlat(False)
        self.pb_start.setObjectName(_fromUtf8("pb_start"))
        self.gb_log = QtGui.QGroupBox(self.tab_basic)
        self.gb_log.setGeometry(QtCore.QRect(10, 260, 571, 131))
        self.gb_log.setObjectName(_fromUtf8("gb_log"))
        self.te_log = QtGui.QTextEdit(self.gb_log)
        self.te_log.setGeometry(QtCore.QRect(10, 20, 531, 101))
        self.te_log.setReadOnly(True)
        self.te_log.setObjectName(_fromUtf8("te_log"))
        self.gb_log.raise_()
        self.gb_general.raise_()
        self.pb_start.raise_()
        self.Credentials.addTab(self.tab_basic, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.gb_optional = QtGui.QGroupBox(self.tab_advanced)
        self.gb_optional.setGeometry(QtCore.QRect(30, 30, 511, 301))
        self.gb_optional.setObjectName(_fromUtf8("gb_optional"))
        self.cb_certs = QtGui.QCheckBox(self.gb_optional)
        self.cb_certs.setGeometry(QtCore.QRect(270, 90, 13, 13))
        self.cb_certs.setText(_fromUtf8(""))
        self.cb_certs.setCheckable(False)
        self.cb_certs.setObjectName(_fromUtf8("cb_certs"))
        self.lbl_sasl1 = QtGui.QLabel(self.gb_optional)
        self.lbl_sasl1.setGeometry(QtCore.QRect(11, 161, 244, 16))
        self.lbl_sasl1.setObjectName(_fromUtf8("lbl_sasl1"))
        self.cb_sasl1 = QtGui.QCheckBox(self.gb_optional)
        self.cb_sasl1.setGeometry(QtCore.QRect(270, 160, 16, 16))
        self.cb_sasl1.setText(_fromUtf8(""))
        self.cb_sasl1.setCheckable(False)
        self.cb_sasl1.setObjectName(_fromUtf8("cb_sasl1"))
        self.lbl_sasl2 = QtGui.QLabel(self.gb_optional)
        self.lbl_sasl2.setGeometry(QtCore.QRect(11, 230, 248, 16))
        self.lbl_sasl2.setObjectName(_fromUtf8("lbl_sasl2"))
        self.cb_sasl2 = QtGui.QCheckBox(self.gb_optional)
        self.cb_sasl2.setGeometry(QtCore.QRect(270, 230, 16, 16))
        self.cb_sasl2.setText(_fromUtf8(""))
        self.cb_sasl2.setCheckable(False)
        self.cb_sasl2.setObjectName(_fromUtf8("cb_sasl2"))
        self.lbl_dialback = QtGui.QLabel(self.gb_optional)
        self.lbl_dialback.setGeometry(QtCore.QRect(20, 40, 73, 16))
        self.lbl_dialback.setObjectName(_fromUtf8("lbl_dialback"))
        self.le_dialback = QtGui.QLineEdit(self.gb_optional)
        self.le_dialback.setGeometry(QtCore.QRect(180, 40, 101, 20))
        self.le_dialback.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.le_dialback.setText(_fromUtf8(""))
        self.le_dialback.setEchoMode(QtGui.QLineEdit.Password)
        self.le_dialback.setObjectName(_fromUtf8("le_dialback"))
        self.lbl_certs = QtGui.QLabel(self.gb_optional)
        self.lbl_certs.setGeometry(QtCore.QRect(11, 93, 185, 16))
        self.lbl_certs.setObjectName(_fromUtf8("lbl_certs"))
        self.Credentials.addTab(self.tab_advanced, _fromUtf8(""))
        self.tab_creds = QtGui.QWidget()
        self.tab_creds.setObjectName(_fromUtf8("tab_creds"))
        self.gb_server1 = QtGui.QGroupBox(self.tab_creds)
        self.gb_server1.setGeometry(QtCore.QRect(10, 30, 551, 161))
        self.gb_server1.setObjectName(_fromUtf8("gb_server1"))
        self.layoutWidget = QtGui.QWidget(self.gb_server1)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 491, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl_appl1 = QtGui.QLabel(self.layoutWidget)
        self.lbl_appl1.setObjectName(_fromUtf8("lbl_appl1"))
        self.horizontalLayout_7.addWidget(self.lbl_appl1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.le_appid1 = QtGui.QLineEdit(self.layoutWidget)
        self.le_appid1.setObjectName(_fromUtf8("le_appid1"))
        self.horizontalLayout_7.addWidget(self.le_appid1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.le_apppw1 = QtGui.QLineEdit(self.layoutWidget)
        self.le_apppw1.setText(_fromUtf8(""))
        self.le_apppw1.setEchoMode(QtGui.QLineEdit.Password)
        self.le_apppw1.setObjectName(_fromUtf8("le_apppw1"))
        self.horizontalLayout_7.addWidget(self.le_apppw1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_plat1 = QtGui.QLabel(self.layoutWidget)
        self.lbl_plat1.setObjectName(_fromUtf8("lbl_plat1"))
        self.horizontalLayout_8.addWidget(self.lbl_plat1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.le_platid1 = QtGui.QLineEdit(self.layoutWidget)
        self.le_platid1.setObjectName(_fromUtf8("le_platid1"))
        self.horizontalLayout_8.addWidget(self.le_platid1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.le_platpw1 = QtGui.QLineEdit(self.layoutWidget)
        self.le_platpw1.setText(_fromUtf8(""))
        self.le_platpw1.setEchoMode(QtGui.QLineEdit.Password)
        self.le_platpw1.setObjectName(_fromUtf8("le_platpw1"))
        self.horizontalLayout_8.addWidget(self.le_platpw1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_creds)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 551, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 491, 101))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lbl_app2 = QtGui.QLabel(self.layoutWidget_2)
        self.lbl_app2.setObjectName(_fromUtf8("lbl_app2"))
        self.horizontalLayout_9.addWidget(self.lbl_app2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.le_appid2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_appid2.setObjectName(_fromUtf8("le_appid2"))
        self.horizontalLayout_9.addWidget(self.le_appid2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.le_apppw2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_apppw2.setText(_fromUtf8(""))
        self.le_apppw2.setEchoMode(QtGui.QLineEdit.Password)
        self.le_apppw2.setObjectName(_fromUtf8("le_apppw2"))
        self.horizontalLayout_9.addWidget(self.le_apppw2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lbl_plat2 = QtGui.QLabel(self.layoutWidget_2)
        self.lbl_plat2.setObjectName(_fromUtf8("lbl_plat2"))
        self.horizontalLayout_10.addWidget(self.lbl_plat2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.le_platid2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_platid2.setObjectName(_fromUtf8("le_platid2"))
        self.horizontalLayout_10.addWidget(self.le_platid2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.le_platpw2 = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_platpw2.setText(_fromUtf8(""))
        self.le_platpw2.setEchoMode(QtGui.QLineEdit.Password)
        self.le_platpw2.setObjectName(_fromUtf8("le_platpw2"))
        self.horizontalLayout_10.addWidget(self.le_platpw2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.cb_copy = QtGui.QCheckBox(self.groupBox_2)
        self.cb_copy.setGeometry(QtCore.QRect(330, 10, 121, 17))
        self.cb_copy.setObjectName(_fromUtf8("cb_copy"))
        self.Credentials.addTab(self.tab_creds, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.Credentials)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpen_Log = QtGui.QAction(MainWindow)
        self.actionOpen_Log.setObjectName(_fromUtf8("actionOpen_Log"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionOpen_Log)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Credentials.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "XMPP Federation Configuration Manager", None))
        self.gb_general.setTitle(_translate("MainWindow", "General", None))
        self.cb_dns.setText(_translate("MainWindow", "DNS Config", None))
        self.lbl_dns.setText(_translate("MainWindow", "DNS Server", None))
        self.le_dns.setPlaceholderText(_translate("MainWindow", "IP Address", None))
        self.lbl_tls.setText(_translate("MainWindow", "Security Mode ", None))
        self.cb_tls.setItemText(0, _translate("MainWindow", "No TLS", None))
        self.cb_tls.setItemText(1, _translate("MainWindow", "TLS Optional", None))
        self.cb_tls.setItemText(2, _translate("MainWindow", "TLS Required", None))
        self.lbl_server1.setText(_translate("MainWindow", "Server 1", None))
        self.le_server1_hn.setPlaceholderText(_translate("MainWindow", "Host Name", None))
        self.le_server1_ip.setPlaceholderText(_translate("MainWindow", "IP Address", None))
        self.le_server1_dn.setPlaceholderText(_translate("MainWindow", "Domain", None))
        self.lbl_server2.setText(_translate("MainWindow", "Server 2", None))
        self.le_server2_hn.setPlaceholderText(_translate("MainWindow", "Host Name", None))
        self.le_server2_ip.setPlaceholderText(_translate("MainWindow", "IP Address", None))
        self.le_server2_dn.setPlaceholderText(_translate("MainWindow", "Domain", None))
        self.cb_cup.setText(_translate("MainWindow", "IM & P Config", None))
        self.pb_start.setText(_translate("MainWindow", "Start", None))
        self.gb_log.setTitle(_translate("MainWindow", "Log", None))
        self.Credentials.setTabText(self.Credentials.indexOf(self.tab_basic), _translate("MainWindow", "Basic", None))
        self.gb_optional.setTitle(_translate("MainWindow", "Optional", None))
        self.lbl_sasl1.setText(_translate("MainWindow", "Enable SASL EXTERNAL on all incoming connections", None))
        self.lbl_sasl2.setText(_translate("MainWindow", "Enable SASL EXTERNAL on all outgoing connections ", None))
        self.lbl_dialback.setText(_translate("MainWindow", "Dialback Secret", None))
        self.le_dialback.setPlaceholderText(_translate("MainWindow", "1234", None))
        self.lbl_certs.setText(_translate("MainWindow", "Require client-side security certificates", None))
        self.Credentials.setTabText(self.Credentials.indexOf(self.tab_advanced), _translate("MainWindow", "Advanced", None))
        self.gb_server1.setTitle(_translate("MainWindow", "Server 1", None))
        self.lbl_appl1.setText(_translate("MainWindow", "Application", None))
        self.le_appid1.setPlaceholderText(_translate("MainWindow", "User Name", None))
        self.le_apppw1.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.lbl_plat1.setText(_translate("MainWindow", "Platform    ", None))
        self.le_platid1.setPlaceholderText(_translate("MainWindow", "User Name", None))
        self.le_platpw1.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Server 2", None))
        self.lbl_app2.setText(_translate("MainWindow", "Application", None))
        self.le_appid2.setPlaceholderText(_translate("MainWindow", "User Name", None))
        self.le_apppw2.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.lbl_plat2.setText(_translate("MainWindow", "Platform    ", None))
        self.le_platid2.setPlaceholderText(_translate("MainWindow", "User Name", None))
        self.le_platpw2.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.cb_copy.setText(_translate("MainWindow", "Copy from Server 1", None))
        self.Credentials.setTabText(self.Credentials.indexOf(self.tab_creds), _translate("MainWindow", "Credentials", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionOpen_Log.setText(_translate("MainWindow", "Open Log", None))
        self.action_Close.setText(_translate("MainWindow", "@Close", None))

import icons_rc
